language: node_js
node_js:
   - '12'

cache:
  yarn: true
  directories:
    - node_modules

dist: trusty
sudo: required
branches:
only:
  - master
  - features
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - npm install -g @angular/cli
install:
  - yarn
script:
  - yarn build:ci
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/ng-mychat
  on:
    branch: features