language: node_js
node_js:
   - '12'

cache:
  directories:
     - ./node_modules

dist: trusty
sudo: required
branches:
only:
  - master
  - features
before_script:
  - npm install -g @angular/cli
  - npm install -g yarn
install:
  - yarn
script:
  - yarn build:ci
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/ng-mychat
  on:
    branch: features